/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const Suspense: typeof import('react').Suspense
  const allDifficultyConfig: typeof import('./config/difficulty').allDifficultyConfig
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const cn: typeof import('./lib/utils').cn
  const countOptions: typeof import('./config/exam').countOptions
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const difficultyConfig: typeof import('./config/difficulty').difficultyConfig
  const difficultyOptions: typeof import('./config/difficulty').difficultyOptions
  const durationOptions: typeof import('./config/exam').durationOptions
  const evaluateAnswerScore: typeof import('./lib/scoring').evaluateAnswerScore
  const examDefaultConfig: typeof import('./config/exam').examDefaultConfig
  const forwardRef: typeof import('react').forwardRef
  const getScoreLevel: typeof import('./config/score').getScoreLevel
  const iconMap: typeof import('./config/icons').iconMap
  const isAnswerCorrect: typeof import('./lib/scoring').isAnswerCorrect
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const passScore: typeof import('./config/score').passScore
  const pathLevelConfig: typeof import('./config/learningPath').pathLevelConfig
  const scoreLevelConfig: typeof import('./config/score').scoreLevelConfig
  const scoreLevelThresholds: typeof import('./config/score').scoreLevelThresholds
  const scoringWeights: typeof import('./config/score').scoringWeights
  const severityConfig: typeof import('./config/severity').severityConfig
  const startTransition: typeof import('react').startTransition
  const stepTypeConfig: typeof import('./config/learningPath').stepTypeConfig
  const timeWarningThreshold: typeof import('./config/exam').timeWarningThreshold
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDelayedLoading: typeof import('./hooks/useDelayedLoading').useDelayedLoading
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useExamStore: typeof import('./store/useExamStore').useExamStore
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLearningPathStore: typeof import('./store/useLearningPathStore').useLearningPathStore
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTheme: typeof import('./hooks/useTheme').useTheme
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { DifficultyConfig } from './config/difficulty'
  import('./config/difficulty')
  // @ts-ignore
  export type { SeverityConfig } from './config/severity'
  import('./config/severity')
  // @ts-ignore
  export type { ScoreLevel, ScoreLevelConfig, ScoreLevelThreshold } from './config/score'
  import('./config/score')
  // @ts-ignore
  export type { StepType, StepTypeConfig, PathLevel, PathLevelConfig } from './config/learningPath'
  import('./config/learningPath')
  // @ts-ignore
  export type { ScoreDetail } from './lib/scoring'
  import('./lib/scoring')
}
